const page_id = "municipios";
const default_uf = "SP";
const default_mun = "Sao_Paulo";
const default_verb = "São Paulo";
const locale =
    [ 
        { prep: "em", uf: "SP", mun:"Sao_Paulo",             verbose: "São Paulo",             has_modelogro: true,  has_td: true  },
        { prep: "em", uf: "SP", mun:"Jundiai",               verbose: "Jundiaí",               has_modelogro: false, has_td: false },
        { prep: "em", uf: "MG", mun:"Belo_Horizonte",        verbose: "Belo Horizonte",        has_modelogro: false, has_td: false  },
        { prep: "no", uf: "RJ", mun:"Rio_de_Janeiro",        verbose: "Rio de Janeiro",        has_modelogro: false, has_td: true  },
        { prep: "em", uf: "SC", mun:"Florianopolis",         verbose: "Florianópolis",         has_modelogro: false, has_td: false },
        { prep: "em", uf: "PB", mun:"Joao_Pessoa",           verbose: "João Pessoa",           has_modelogro: false, has_td: false  },
        { prep: "em", uf: "GO", mun:"Goiania",               verbose: "Goiânia",               has_modelogro: false, has_td: false },
        { prep: "em", uf: "AM", mun:"Itapiranga",            verbose: "Itapiranga",            has_modelogro: false, has_td: true  },
        { prep: "em", uf: "AM", mun:"Manaus",                verbose: "Manaus",                has_modelogro: false, has_td: false },
        { prep: "em", uf: "AM", mun:"Santo_Antonio_do_Ica",  verbose: "Santo Antônio do Içá",  has_modelogro: false, has_td: true  },
        { prep: "em", uf: "AM", mun:"Tabatinga",             verbose: "Tabatinga",             has_modelogro: false, has_td: false },
        { prep: "em", uf: "PR", mun:"Curitiba",              verbose: "Curitiba",              has_modelogro: false, has_td: false },
        { prep: "em", uf: "SP", mun:"Santos",                verbose: "Santos",                has_modelogro: false, has_td: true  },
        { prep: "em", uf: "RS", mun:"Caxias_do_Sul",         verbose: "Caxias do Sul",         has_modelogro: false, has_td: true  },
        { prep: "em", uf: "RS", mun:"Porto_Alegre",          verbose: "Porto Alegre",          has_modelogro: false, has_td: false },
        { prep: "em", uf: "SP", mun:"Sao_Bernardo_do_Campo", verbose: "São Bernardo do Campo", has_modelogro: false, has_td: false  },
        { prep: "em", uf: "SP", mun:"Guarulhos",             verbose: "Guarulhos",             has_modelogro: false, has_td: false },
        { prep: "em", uf: "SP", mun:"Osasco",                verbose: "Osasco",                has_modelogro: false, has_td: false },
        { prep: "em", uf: "PA", mun:"Belem",                 verbose: "Belém",                 has_modelogro: false, has_td: true  },
        { prep: "em", uf: "PE", mun:"Recife",                verbose: "Recife",                has_modelogro: false, has_td: false },
        { prep: "em", uf: "CE", mun:"Itapipoca",             verbose: "Itapipoca",             has_modelogro: false, has_td: false },
        { prep: "em", uf: "CE", mun:"Fortaleza",             verbose: "Fortaleza",             has_modelogro: false, has_td: false },
        { prep: "em", uf: "CE", mun:"Sobral",                verbose: "Sobral",                has_modelogro: false, has_td: true  },
        { prep: "em", uf: "RJ", mun:"Duque_de_Caxias",       verbose: "Duque de Caxias",       has_modelogro: false, has_td: false },
        { prep: "em", uf: "BA", mun:"Ilheus",                verbose: "Ilhéus",                has_modelogro: false, has_td: false },
        { prep: "em", uf: "BA", mun:"Itabuna",               verbose: "Itabuna",               has_modelogro: false, has_td: true  },
        { prep: "em", uf: "BA", mun:"Salvador",              verbose: "Salvador",              has_modelogro: false, has_td: true  },
        { prep: "em", uf: "PA", mun:"Ananindeua",            verbose: "Ananindeua",            has_modelogro: false, has_td: true  },
        { prep: "em", uf: "PA", mun:"Santarem",              verbose: "Santarém",              has_modelogro: false, has_td: true  },
        { prep: "em", uf: "SP", mun:"Santo_Andre",           verbose: "Santo André",           has_modelogro: false, has_td: true  },
        { prep: "em", uf: "MA", mun:"Sao_Luis",              verbose: "São Luís",              has_modelogro: false, has_td: true  },
        { prep: "em", uf: "ES", mun:"Vitoria",               verbose: "Vitória",               has_modelogro: false, has_td: false },
        { prep: "em", uf: "ES", mun:"Alegre",                verbose: "Alegre",                has_modelogro: false, has_td: true  },
        { prep: "em", uf: "AP", mun:"Macapa",                verbose: "Macapá",                has_modelogro: false, has_td: true  },
        { prep: "em", uf: "AM", mun:"Manacapuru",            verbose: "Manacapuru",            has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RJ", mun:"Niteroi",               verbose: "Niterói",               has_modelogro: false, has_td: false },
        { prep: "em", uf: "SP", mun:"Ribeirao_Preto",        verbose: "Ribeirão Preto",        has_modelogro: false, has_td: false  },
        { prep: "em", uf: "SP", mun:"Americana",             verbose: "Americana",             has_modelogro: false, has_td: false  },
        { prep: "em", uf: "SP", mun:"Santa_Barbara_dOeste",  verbose: "Santa Bárbara d'Oeste", has_modelogro: false, has_td: false  },
        { prep: "em", uf: "SP", mun:"Barueri",               verbose: "Barueri",               has_modelogro: false, has_td: false  },
        { prep: "em", uf: "SP", mun:"Botucatu",              verbose: "Botucatu",              has_modelogro: false, has_td: false  },
        { prep: "em", uf: "PR", mun:"Londrina",              verbose: "Londrina",              has_modelogro: false, has_td: true  },
        { prep: "em", uf: "PR", mun:"Maringa",               verbose: "Maringá",               has_modelogro: false, has_td: false  },
        { prep: "em", uf: "PE", mun:"Olinda",                verbose: "Olinda",                has_modelogro: false, has_td: false  },
        { prep: "em", uf: "DF", mun:"Brasilia",              verbose: "Brasília",              has_modelogro: false, has_td: false  },
        { prep: "em", uf: "AC", mun:"Rio_Branco",            verbose: "Rio Branco",            has_modelogro: false, has_td: false  },
        { prep: "em", uf: "AL", mun:"Maceio",                verbose: "Maceió",                has_modelogro: false, has_td: false  },
        { prep: "em", uf: "CE", mun:"Maracanau",             verbose: "Maracanaú",             has_modelogro: false, has_td: false  },
        { prep: "em", uf: "ES", mun:"Serra",                 verbose: "Serra",                 has_modelogro: false, has_td: false  },
        { prep: "em", uf: "MA", mun:"Acailandia",            verbose: "Açailândia",            has_modelogro: false, has_td: true  },
        { prep: "em", uf: "MA", mun:"Alto_Alegre_do_Pindare",verbose: "Alto Alegre do Pindaré",has_modelogro: false, has_td: true  },
        { prep: "em", uf: "MA", mun:"Imperatriz",            verbose: "Imperatriz",            has_modelogro: false, has_td: false  },
        { prep: "em", uf: "MS", mun:"Campo_Grande",          verbose: "Campo Grande",          has_modelogro: false, has_td: false  },
        { prep: "em", uf: "MT", mun:"Cuiaba",                verbose: "Cuiabá",                has_modelogro: false, has_td: false  },
        { prep: "em", uf: "PE", mun:"Cabo_de_Santo_Agostinho",verbose: "Cabo de Santo Agostinho",has_modelogro: false, has_td: true  },
        { prep: "em", uf: "PE", mun:"Jaboatao_dos_Guararapes",verbose: "Jaboatão dos Guararapes",has_modelogro:false,has_td: false  },
        { prep: "em", uf: "PE", mun:"Paulista",              verbose: "Paulista",              has_modelogro: false, has_td: false  },
        { prep: "em", uf: "PI", mun:"Parnaiba",              verbose: "Parnaíba",              has_modelogro: false, has_td: true  },
        { prep: "em", uf: "PI", mun:"Teresina",              verbose: "Teresina",              has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RJ", mun:"Nova_Iguacu",           verbose: "Nova Iguaçu",           has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RJ", mun:"Sao_Goncalo",           verbose: "São Gonçalo",           has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RJ", mun:"Belford_Roxo",          verbose: "Belford Roxo",          has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RN", mun:"Mossoro",               verbose: "Mossoró",               has_modelogro: false, has_td: true  },
        { prep: "em", uf: "RN", mun:"Natal",                 verbose: "Natal",                 has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RO", mun:"Porto_Velho",           verbose: "Porto Velho",           has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RR", mun:"Boa_Vista",             verbose: "Boa Vista",             has_modelogro: false, has_td: false  },
        { prep: "em", uf: "SE", mun:"Aracaju",               verbose: "Aracaju",               has_modelogro: false, has_td: false  },
        { prep: "em", uf: "TO", mun:"Palmas",                verbose: "Palmas",                has_modelogro: false, has_td: false  },
        { prep: "em", uf: "SP", mun:"Taboao_da_Serra",       verbose: "Taboão da Serra",       has_modelogro: false, has_td: false  },
        { prep: "em", uf: "SP", mun:"Diadema",               verbose: "Diadema",               has_modelogro: false, has_td: false  },
        { prep: "em", uf: "SP", mun:"Maua",                  verbose: "Mauá",                  has_modelogro: false, has_td: false  },
        { prep: "em", uf: "SP", mun:"Sao_Caetano_do_Sul",    verbose: "São Caetano do Sul",    has_modelogro: false, has_td: false  },
        { prep: "em", uf: "SP", mun:"Sao_Jose_dos_Campos",   verbose: "São José dos Campos",   has_modelogro: false, has_td: false  },
        { prep: "em", uf: "SP", mun:"Sorocaba",              verbose: "Sorocaba",              has_modelogro: false, has_td: false  },
        { prep: "em", uf: "SP", mun:"Campinas",              verbose: "Campinas",              has_modelogro: false, has_td: false  },
	{ prep: "em", uf: "SP", mun:"Votuporanga",              verbose: "Votuporanga",              has_modelogro: false, has_td: false  }
    ];
