const page_id = "DRS";
const default_uf = "SP";
const default_mun = "Grande_Sao_Paulo";
const default_verb = "Grande São Paulo";
const locale =
    [
        { prep: "na", uf: "SP", mun:"Grande_Sao_Paulo",      verbose: "Grande São Paulo",      has_modelogro: true, has_td: true  },
        { prep: "em", uf: "SP", mun:"Aracatuba",             verbose: "Araçatuba",             has_modelogro: true, has_td: false },
        { prep: "em", uf: "SP", mun:"Araraquara",            verbose: "Araraquara",            has_modelogro: true, has_td: false },
        { prep: "na", uf: "SP", mun:"Baixada_Santista",      verbose: "Baixada Santista",      has_modelogro: true, has_td: false },
        { prep: "em", uf: "SP", mun:"Barretos",              verbose: "Barretos",              has_modelogro: true, has_td: false },
        { prep: "em", uf: "SP", mun:"Bauru",                 verbose: "Bauru",                 has_modelogro: true, has_td: false },
        { prep: "em", uf: "SP", mun:"Campinas",              verbose: "Campinas",              has_modelogro: true, has_td: false },
        { prep: "em", uf: "SP", mun:"Franca",                verbose: "Franca",                has_modelogro: true, has_td: false },
        { prep: "em", uf: "SP", mun:"Marilia",               verbose: "Marília",               has_modelogro: true, has_td: false },
        { prep: "em", uf: "SP", mun:"Piracicaba",            verbose: "Piracicaba",            has_modelogro: true, has_td: false },
        { prep: "em", uf: "SP", mun:"Presidente_Prudente",   verbose: "Presidente Prudente",   has_modelogro: true, has_td: false },
        { prep: "em", uf: "SP", mun:"Registro",              verbose: "Registro",              has_modelogro: true, has_td: false },
        { prep: "em", uf: "SP", mun:"Ribeirao_Preto",        verbose: "Ribeirão Preto",        has_modelogro: true, has_td: false },
        { prep: "em", uf: "SP", mun:"Sao_Joao_da_Boa_Vista", verbose: "São João da Boa Vista", has_modelogro: true, has_td: false },
        { prep: "em", uf: "SP", mun:"Sao_Jose_do_Rio_Preto", verbose: "São José do Rio Preto", has_modelogro: true, has_td: false },
        { prep: "em", uf: "SP", mun:"Sorocaba",              verbose: "Sorocaba",              has_modelogro: true, has_td: false },
        { prep: "em", uf: "SP", mun:"Taubate",               verbose: "Taubaté",               has_modelogro: true, has_td: false },
        { prep: "em", uf: "RS", mun:"Bage",                  verbose: "Bagé",                  has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RS", mun:"Cachoeira_do_Sul",      verbose: "Cachoeira do Sul",      has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RS", mun:"Canoas",                verbose: "Canoas",                has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RS", mun:"Capao_Da_Canoa",        verbose: "Capão Da Canoa",        has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RS", mun:"Caxias_do_Sul",         verbose: "Caxias do Sul",         has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RS", mun:"Cruz_Alta",             verbose: "Cruz Alta",             has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RS", mun:"Erechim",               verbose: "Erechim",               has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RS", mun:"Guaiba",                verbose: "Guaíba",                has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RS", mun:"Ijui",                  verbose: "Ijuí",                  has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RS", mun:"Lajeado",               verbose: "Lajeado",               has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RS", mun:"Novo_Hamburgo",         verbose: "Novo Hamburgo",         has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RS", mun:"Palmeira_das_Missoes",  verbose: "Palmeira das Missões",  has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RS", mun:"Passo_Fundo",           verbose: "Passo Fundo",           has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RS", mun:"Pelotas",               verbose: "Pelotas",               has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RS", mun:"Porto_Alegre",          verbose: "Porto Alegre",          has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RS", mun:"Santa_Cruz_do_Sul",     verbose: "Santa Cruz do Sul",     has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RS", mun:"Santa_Maria",           verbose: "Santa Maria",           has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RS", mun:"Santa_Rosa",            verbose: "Santa Rosa",            has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RS", mun:"Santo_Angelo",          verbose: "Santo Ângelo",          has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RS", mun:"Taquara",               verbose: "Taquara",               has_modelogro: false, has_td: false  },
        { prep: "em", uf: "RS", mun:"Uruguaiana",            verbose: "Uruguaiana",            has_modelogro: false, has_td: false  }
    ];
