---
title: "Observatório COVID-19 SP"
date: "`r format(Sys.time(), '%d de %B de %Y, %H:%M')`"
output:
 flexdashboard::flex_dashboard:
  self_contained: false
  theme: cerulean
  lib_dir: ../libs
  source_code: "https://github.com/covid19br/covid19br.github.io"
  social: menu
  css: [ 'styles.css', 'home.css' ]
  navbar:
    - { title: "Início", href: "../index.html", align: left}
    - { title: "São Paulo", href: "index.html", align: left}
    - { title: "+Info", href: "../informacoes.html", align: left}
    - { title: "Fontes", href: "../fontes.html", align: left}
    - { title: "Na Mídia", href: "../midia.html", align: left}
    - { title: "Sobre", href: "../sobre.html", align: left}
  favicon: favicon.png
  includes:
   after_body: ../../_src/footer.html
   in_header: ../../_src/header.html
---

```{r setOptions, include=FALSE, message=FALSE}
library(flexdashboard)
#library(xtable)
library(knitr)
#library(plotly)
options(OutDec = ',')
knitr::opts_chunk$set(echo=FALSE, warnings=FALSE, message=FALSE, fig.width=3,
                      fig.height=2, fig.align="center")
```

<div class="container">

<div class="item2">
  <h4><a href="projecao.html" id="casos">Quantos casos já temos no estado de São Paulo? Quantos teremos nos próximos dias? </a></h4>
  <a href="projecao.html">
```{r , fig.width = 6, fig.height=4}
plot.forecast.exp
```
  </a>
</div>

<div class="item">
  <h4><a href="propagacao.html" id="tduplica">Quão rápido a doença se propaga?</a></h4>
  
  <a href="propagacao.html">
  
```{r}
plot.tempo.dupl + theme(axis.text.x = element_text(size = 10),
                        axis.title.y = element_text(size = 8))
```
  </a>
</div>

<div class="item">
  <h4><a href="transmissao.html">Para quantas pessoas cada infectado transmite a doença?</a></h4>
  <a href="transmissao.html">
```{r}
plot.estimate.R0 + theme(axis.text.x = element_text(size = 10),
                        axis.title.y = element_text(size = 8))
```
  </a>
</div>

</div>
