---
title: "COVID-19 BR"
header-includes:
  - \usepackage[brazil]{babel}
output: 
  flexdashboard::flex_dashboard:
  theme: spacelab
  source: embed
date: "`r format(Sys.time(), '%d de %B de %Y')`"
---

```{r setOptions, include=FALSE, message=FALSE}
library(zoo)
library(rmarkdown)
library(flexdashboard)
#library(dygraphs)
library(ggplot2)
library(xtable)
library(knitr)
library(EpiEstim)
library(plotly)
## library(googleVis)
options(OutDec = ',')
knitr::opts_chunk$set(echo=FALSE, warnings=FALSE, message=FALSE)
##op <- options(gvis.plot.tag='chart')

################################################################################
## Parametros de formatacao comum aos plots
################################################################################
plot.formatos <- theme_bw()+
    theme(axis.text= element_text(size=12, face="bold"),
          axis.title.y = element_text(size=14, face="bold"))
theme_set(theme_bw())

################################################################################
# DADOS
################################################################################

```


Principal
===================================== 
Column
-------------------------------------
### plot Casos BR

```{r}
################################################################################
## Grafico da serie observada e do previsto pelo modelo exponencial
## para os proximos 5 dias (com intervalo de confiança)
################################################################################
## Serie com observados e previstos
## (gambiarra para ter linha continua no grafico, verificar hel de ggplot.zoo)
ncasos.completa <- c(brasil$casos.acumulados, exp.5d$predito)
plot.forecast.exp <-
    ggplot(ncasos.completa, aes(Index, ncasos.completa)) +
    geom_line(aes(Index, ncasos.completa), color="gray") +
    geom_point(data=brasil, aes(Index, casos.acumulados), size=2) +
    scale_x_date(#breaks=seq(min(time(ncasos.completa)), max(time(ncasos.completa)), by=3),
                date_labels = "%d/%b", name="") +
    ylim(0,max(exp.5d$ic.upp)) +
    geom_point(data=exp.5d, aes(Index,predito), col="blue", size=2) +
    geom_ribbon(data=exp.5d, aes(Index, predito, ymin=ic.low, ymax=ic.upp), fill="blue", alpha=0.25) +
    ylab("Número de casos") +
    plot.formatos

ggplotly(plot.forecast.exp)

```


Column
-------------------------------------
### Plot R0

```{r}
plot.estimate.R0 <- plot(res.uncertain.si, "R", legend=TRUE)
plot.estimate.R0
#    plot.formatos
#ggplotly(plot.estimate.R0)

```

### Plot taxa de duplicação

```{r}
plot.tempo.dupl <-
    ggplot(tempos.duplicacao, aes(Index, estimativa)) +
    geom_line(size = 1.25) +
    geom_ribbon(aes(ymin = ic.inf, ymax = ic.sup), alpha = 0.25) +
    scale_x_date(#breaks=seq(min(time(ncasos.completa)), max(time(ncasos.completa)), by=3),
                date_labels = "%d/%b", name="") +
    ylab("Tempo de duplicação (dias)") +
    plot.formatos

ggplotly(plot.tempo.dupl)

```

```{r child = 'redes.Rmd'}
```

```{r child = 'informacoes.Rmd'}
```

```{r child = 'sobre.Rmd'}
```

